# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
    #- step:
        #name: Deploy to production
        #deployment: production
        # trigger: manual  # Uncomment to make this a manual deployment.
        #script:
          #- pipe: atlassian/ssh-run:0.2.2
            #variables:
              #SSH_USER: 'd4a'
              #SERVER: '108.61.86.53'
              #COMMAND: './deployFrontend.sh'

          


